// <auto-generated />
namespace MOE.Common.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DataAggregationUI : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DataAggregationUI));
        
        string IMigrationMetadata.Id
        {
            get { return "201710272056348_DataAggregationUI"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
