// <auto-generated />
namespace MOE.Common.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _401 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_401));
        
        string IMigrationMetadata.Id
        {
            get { return "201702162037176_4.0.1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
