//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace MOE.Common.Data {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("LinkPivot")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class LinkPivot : global::System.Data.DataSet {
        
        private LinkPivotAdjustmentDataTable tableLinkPivotAdjustment;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        public LinkPivot() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        protected LinkPivot(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["LinkPivotAdjustment"] != null)) {
                    base.Tables.Add(new LinkPivotAdjustmentDataTable(ds.Tables["LinkPivotAdjustment"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public LinkPivotAdjustmentDataTable LinkPivotAdjustment {
            get {
                return this.tableLinkPivotAdjustment;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        public override global::System.Data.DataSet Clone() {
            LinkPivot cln = ((LinkPivot)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["LinkPivotAdjustment"] != null)) {
                    base.Tables.Add(new LinkPivotAdjustmentDataTable(ds.Tables["LinkPivotAdjustment"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        internal void InitVars(bool initTable) {
            this.tableLinkPivotAdjustment = ((LinkPivotAdjustmentDataTable)(base.Tables["LinkPivotAdjustment"]));
            if ((initTable == true)) {
                if ((this.tableLinkPivotAdjustment != null)) {
                    this.tableLinkPivotAdjustment.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        private void InitClass() {
            this.DataSetName = "LinkPivot";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/LinkPivot.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tableLinkPivotAdjustment = new LinkPivotAdjustmentDataTable();
            base.Tables.Add(this.tableLinkPivotAdjustment);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        private bool ShouldSerializeLinkPivotAdjustment() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            LinkPivot ds = new LinkPivot();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        public delegate void LinkPivotAdjustmentRowChangeEventHandler(object sender, LinkPivotAdjustmentRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class LinkPivotAdjustmentDataTable : global::System.Data.TypedTableBase<LinkPivotAdjustmentRow> {
            
            private global::System.Data.DataColumn columnSignalId;
            
            private global::System.Data.DataColumn columnDelta;
            
            private global::System.Data.DataColumn columnAdjustment;
            
            private global::System.Data.DataColumn columnPAOGUpstreamBefore;
            
            private global::System.Data.DataColumn columnPAOGDownstreamBefore;
            
            private global::System.Data.DataColumn columnAOGUpstreamBefore;
            
            private global::System.Data.DataColumn columnAOGDownstreamBefore;
            
            private global::System.Data.DataColumn columnPAOGUpstreamPredicted;
            
            private global::System.Data.DataColumn columnPAOGDownstreamPredicted;
            
            private global::System.Data.DataColumn columnAOGUpstreamPredicted;
            
            private global::System.Data.DataColumn columnAOGDownstreamPredicted;
            
            private global::System.Data.DataColumn columnLocation;
            
            private global::System.Data.DataColumn columnDownstreamSignalID;
            
            private global::System.Data.DataColumn columnDownstreamApproachDirection;
            
            private global::System.Data.DataColumn columnUpstreamApproachDirection;
            
            private global::System.Data.DataColumn columnResultChartLocation;
            
            private global::System.Data.DataColumn columnDownstreamLocation;
            
            private global::System.Data.DataColumn columnAOGTotalBefore;
            
            private global::System.Data.DataColumn columnPAOGToatalBefore;
            
            private global::System.Data.DataColumn columnAOGTotalPredicted;
            
            private global::System.Data.DataColumn columnPAOGTotalPredicted;
            
            private global::System.Data.DataColumn columnLinkNumber;
            
            private global::System.Data.DataColumn columnDownstreamVolume;
            
            private global::System.Data.DataColumn columnUpstreamVolume;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public LinkPivotAdjustmentDataTable() {
                this.TableName = "LinkPivotAdjustment";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            internal LinkPivotAdjustmentDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected LinkPivotAdjustmentDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn SignalIdColumn {
                get {
                    return this.columnSignalId;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn DeltaColumn {
                get {
                    return this.columnDelta;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn AdjustmentColumn {
                get {
                    return this.columnAdjustment;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn PAOGUpstreamBeforeColumn {
                get {
                    return this.columnPAOGUpstreamBefore;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn PAOGDownstreamBeforeColumn {
                get {
                    return this.columnPAOGDownstreamBefore;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn AOGUpstreamBeforeColumn {
                get {
                    return this.columnAOGUpstreamBefore;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn AOGDownstreamBeforeColumn {
                get {
                    return this.columnAOGDownstreamBefore;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn PAOGUpstreamPredictedColumn {
                get {
                    return this.columnPAOGUpstreamPredicted;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn PAOGDownstreamPredictedColumn {
                get {
                    return this.columnPAOGDownstreamPredicted;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn AOGUpstreamPredictedColumn {
                get {
                    return this.columnAOGUpstreamPredicted;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn AOGDownstreamPredictedColumn {
                get {
                    return this.columnAOGDownstreamPredicted;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn LocationColumn {
                get {
                    return this.columnLocation;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn DownstreamSignalIDColumn {
                get {
                    return this.columnDownstreamSignalID;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn DownstreamApproachDirectionColumn {
                get {
                    return this.columnDownstreamApproachDirection;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn UpstreamApproachDirectionColumn {
                get {
                    return this.columnUpstreamApproachDirection;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn ResultChartLocationColumn {
                get {
                    return this.columnResultChartLocation;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn DownstreamLocationColumn {
                get {
                    return this.columnDownstreamLocation;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn AOGTotalBeforeColumn {
                get {
                    return this.columnAOGTotalBefore;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn PAOGToatalBeforeColumn {
                get {
                    return this.columnPAOGToatalBefore;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn AOGTotalPredictedColumn {
                get {
                    return this.columnAOGTotalPredicted;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn PAOGTotalPredictedColumn {
                get {
                    return this.columnPAOGTotalPredicted;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn LinkNumberColumn {
                get {
                    return this.columnLinkNumber;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn DownstreamVolumeColumn {
                get {
                    return this.columnDownstreamVolume;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn UpstreamVolumeColumn {
                get {
                    return this.columnUpstreamVolume;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public LinkPivotAdjustmentRow this[int index] {
                get {
                    return ((LinkPivotAdjustmentRow)(this.Rows[index]));
                }
            }
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public event LinkPivotAdjustmentRowChangeEventHandler LinkPivotAdjustmentRowChanging;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public event LinkPivotAdjustmentRowChangeEventHandler LinkPivotAdjustmentRowChanged;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public event LinkPivotAdjustmentRowChangeEventHandler LinkPivotAdjustmentRowDeleting;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public event LinkPivotAdjustmentRowChangeEventHandler LinkPivotAdjustmentRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void AddLinkPivotAdjustmentRow(LinkPivotAdjustmentRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public LinkPivotAdjustmentRow AddLinkPivotAdjustmentRow(
                        string SignalId, 
                        int Delta, 
                        int Adjustment, 
                        double PAOGUpstreamBefore, 
                        double PAOGDownstreamBefore, 
                        double AOGUpstreamBefore, 
                        double AOGDownstreamBefore, 
                        double PAOGUpstreamPredicted, 
                        double PAOGDownstreamPredicted, 
                        double AOGUpstreamPredicted, 
                        double AOGDownstreamPredicted, 
                        string Location, 
                        string DownstreamSignalID, 
                        string DownstreamApproachDirection, 
                        string UpstreamApproachDirection, 
                        string ResultChartLocation, 
                        string DownstreamLocation, 
                        double AOGTotalBefore, 
                        double PAOGToatalBefore, 
                        double AOGTotalPredicted, 
                        double PAOGTotalPredicted, 
                        int LinkNumber, 
                        double DownstreamVolume, 
                        double UpstreamVolume) {
                LinkPivotAdjustmentRow rowLinkPivotAdjustmentRow = ((LinkPivotAdjustmentRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        SignalId,
                        Delta,
                        Adjustment,
                        PAOGUpstreamBefore,
                        PAOGDownstreamBefore,
                        AOGUpstreamBefore,
                        AOGDownstreamBefore,
                        PAOGUpstreamPredicted,
                        PAOGDownstreamPredicted,
                        AOGUpstreamPredicted,
                        AOGDownstreamPredicted,
                        Location,
                        DownstreamSignalID,
                        DownstreamApproachDirection,
                        UpstreamApproachDirection,
                        ResultChartLocation,
                        DownstreamLocation,
                        AOGTotalBefore,
                        PAOGToatalBefore,
                        AOGTotalPredicted,
                        PAOGTotalPredicted,
                        LinkNumber,
                        DownstreamVolume,
                        UpstreamVolume};
                rowLinkPivotAdjustmentRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowLinkPivotAdjustmentRow);
                return rowLinkPivotAdjustmentRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public override global::System.Data.DataTable Clone() {
                LinkPivotAdjustmentDataTable cln = ((LinkPivotAdjustmentDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected override global::System.Data.DataTable CreateInstance() {
                return new LinkPivotAdjustmentDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            internal void InitVars() {
                this.columnSignalId = base.Columns["SignalId"];
                this.columnDelta = base.Columns["Delta"];
                this.columnAdjustment = base.Columns["Adjustment"];
                this.columnPAOGUpstreamBefore = base.Columns["PAOGUpstreamBefore"];
                this.columnPAOGDownstreamBefore = base.Columns["PAOGDownstreamBefore"];
                this.columnAOGUpstreamBefore = base.Columns["AOGUpstreamBefore"];
                this.columnAOGDownstreamBefore = base.Columns["AOGDownstreamBefore"];
                this.columnPAOGUpstreamPredicted = base.Columns["PAOGUpstreamPredicted"];
                this.columnPAOGDownstreamPredicted = base.Columns["PAOGDownstreamPredicted"];
                this.columnAOGUpstreamPredicted = base.Columns["AOGUpstreamPredicted"];
                this.columnAOGDownstreamPredicted = base.Columns["AOGDownstreamPredicted"];
                this.columnLocation = base.Columns["Location"];
                this.columnDownstreamSignalID = base.Columns["DownstreamSignalID"];
                this.columnDownstreamApproachDirection = base.Columns["DownstreamApproachDirection"];
                this.columnUpstreamApproachDirection = base.Columns["UpstreamApproachDirection"];
                this.columnResultChartLocation = base.Columns["ResultChartLocation"];
                this.columnDownstreamLocation = base.Columns["DownstreamLocation"];
                this.columnAOGTotalBefore = base.Columns["AOGTotalBefore"];
                this.columnPAOGToatalBefore = base.Columns["PAOGToatalBefore"];
                this.columnAOGTotalPredicted = base.Columns["AOGTotalPredicted"];
                this.columnPAOGTotalPredicted = base.Columns["PAOGTotalPredicted"];
                this.columnLinkNumber = base.Columns["LinkNumber"];
                this.columnDownstreamVolume = base.Columns["DownstreamVolume"];
                this.columnUpstreamVolume = base.Columns["UpstreamVolume"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            private void InitClass() {
                this.columnSignalId = new global::System.Data.DataColumn("SignalId", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSignalId);
                this.columnDelta = new global::System.Data.DataColumn("Delta", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDelta);
                this.columnAdjustment = new global::System.Data.DataColumn("Adjustment", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnAdjustment);
                this.columnPAOGUpstreamBefore = new global::System.Data.DataColumn("PAOGUpstreamBefore", typeof(double), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPAOGUpstreamBefore);
                this.columnPAOGDownstreamBefore = new global::System.Data.DataColumn("PAOGDownstreamBefore", typeof(double), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPAOGDownstreamBefore);
                this.columnAOGUpstreamBefore = new global::System.Data.DataColumn("AOGUpstreamBefore", typeof(double), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnAOGUpstreamBefore);
                this.columnAOGDownstreamBefore = new global::System.Data.DataColumn("AOGDownstreamBefore", typeof(double), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnAOGDownstreamBefore);
                this.columnPAOGUpstreamPredicted = new global::System.Data.DataColumn("PAOGUpstreamPredicted", typeof(double), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPAOGUpstreamPredicted);
                this.columnPAOGDownstreamPredicted = new global::System.Data.DataColumn("PAOGDownstreamPredicted", typeof(double), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPAOGDownstreamPredicted);
                this.columnAOGUpstreamPredicted = new global::System.Data.DataColumn("AOGUpstreamPredicted", typeof(double), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnAOGUpstreamPredicted);
                this.columnAOGDownstreamPredicted = new global::System.Data.DataColumn("AOGDownstreamPredicted", typeof(double), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnAOGDownstreamPredicted);
                this.columnLocation = new global::System.Data.DataColumn("Location", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnLocation);
                this.columnDownstreamSignalID = new global::System.Data.DataColumn("DownstreamSignalID", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDownstreamSignalID);
                this.columnDownstreamApproachDirection = new global::System.Data.DataColumn("DownstreamApproachDirection", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDownstreamApproachDirection);
                this.columnUpstreamApproachDirection = new global::System.Data.DataColumn("UpstreamApproachDirection", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnUpstreamApproachDirection);
                this.columnResultChartLocation = new global::System.Data.DataColumn("ResultChartLocation", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnResultChartLocation);
                this.columnDownstreamLocation = new global::System.Data.DataColumn("DownstreamLocation", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDownstreamLocation);
                this.columnAOGTotalBefore = new global::System.Data.DataColumn("AOGTotalBefore", typeof(double), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnAOGTotalBefore);
                this.columnPAOGToatalBefore = new global::System.Data.DataColumn("PAOGToatalBefore", typeof(double), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPAOGToatalBefore);
                this.columnAOGTotalPredicted = new global::System.Data.DataColumn("AOGTotalPredicted", typeof(double), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnAOGTotalPredicted);
                this.columnPAOGTotalPredicted = new global::System.Data.DataColumn("PAOGTotalPredicted", typeof(double), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPAOGTotalPredicted);
                this.columnLinkNumber = new global::System.Data.DataColumn("LinkNumber", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnLinkNumber);
                this.columnDownstreamVolume = new global::System.Data.DataColumn("DownstreamVolume", typeof(double), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDownstreamVolume);
                this.columnUpstreamVolume = new global::System.Data.DataColumn("UpstreamVolume", typeof(double), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnUpstreamVolume);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public LinkPivotAdjustmentRow NewLinkPivotAdjustmentRow() {
                return ((LinkPivotAdjustmentRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new LinkPivotAdjustmentRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected override global::System.Type GetRowType() {
                return typeof(LinkPivotAdjustmentRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.LinkPivotAdjustmentRowChanged != null)) {
                    this.LinkPivotAdjustmentRowChanged(this, new LinkPivotAdjustmentRowChangeEvent(((LinkPivotAdjustmentRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.LinkPivotAdjustmentRowChanging != null)) {
                    this.LinkPivotAdjustmentRowChanging(this, new LinkPivotAdjustmentRowChangeEvent(((LinkPivotAdjustmentRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.LinkPivotAdjustmentRowDeleted != null)) {
                    this.LinkPivotAdjustmentRowDeleted(this, new LinkPivotAdjustmentRowChangeEvent(((LinkPivotAdjustmentRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.LinkPivotAdjustmentRowDeleting != null)) {
                    this.LinkPivotAdjustmentRowDeleting(this, new LinkPivotAdjustmentRowChangeEvent(((LinkPivotAdjustmentRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void RemoveLinkPivotAdjustmentRow(LinkPivotAdjustmentRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                LinkPivot ds = new LinkPivot();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "LinkPivotAdjustmentDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        public partial class LinkPivotAdjustmentRow : global::System.Data.DataRow {
            
            private LinkPivotAdjustmentDataTable tableLinkPivotAdjustment;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            internal LinkPivotAdjustmentRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableLinkPivotAdjustment = ((LinkPivotAdjustmentDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string SignalId {
                get {
                    try {
                        return ((string)(this[this.tableLinkPivotAdjustment.SignalIdColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'SignalId\' in table \'LinkPivotAdjustment\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableLinkPivotAdjustment.SignalIdColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public int Delta {
                get {
                    try {
                        return ((int)(this[this.tableLinkPivotAdjustment.DeltaColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Delta\' in table \'LinkPivotAdjustment\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableLinkPivotAdjustment.DeltaColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public int Adjustment {
                get {
                    try {
                        return ((int)(this[this.tableLinkPivotAdjustment.AdjustmentColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Adjustment\' in table \'LinkPivotAdjustment\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableLinkPivotAdjustment.AdjustmentColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public double PAOGUpstreamBefore {
                get {
                    try {
                        return ((double)(this[this.tableLinkPivotAdjustment.PAOGUpstreamBeforeColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'PAOGUpstreamBefore\' in table \'LinkPivotAdjustment\' is DBNul" +
                                "l.", e);
                    }
                }
                set {
                    this[this.tableLinkPivotAdjustment.PAOGUpstreamBeforeColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public double PAOGDownstreamBefore {
                get {
                    try {
                        return ((double)(this[this.tableLinkPivotAdjustment.PAOGDownstreamBeforeColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'PAOGDownstreamBefore\' in table \'LinkPivotAdjustment\' is DBN" +
                                "ull.", e);
                    }
                }
                set {
                    this[this.tableLinkPivotAdjustment.PAOGDownstreamBeforeColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public double AOGUpstreamBefore {
                get {
                    try {
                        return ((double)(this[this.tableLinkPivotAdjustment.AOGUpstreamBeforeColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'AOGUpstreamBefore\' in table \'LinkPivotAdjustment\' is DBNull" +
                                ".", e);
                    }
                }
                set {
                    this[this.tableLinkPivotAdjustment.AOGUpstreamBeforeColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public double AOGDownstreamBefore {
                get {
                    try {
                        return ((double)(this[this.tableLinkPivotAdjustment.AOGDownstreamBeforeColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'AOGDownstreamBefore\' in table \'LinkPivotAdjustment\' is DBNu" +
                                "ll.", e);
                    }
                }
                set {
                    this[this.tableLinkPivotAdjustment.AOGDownstreamBeforeColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public double PAOGUpstreamPredicted {
                get {
                    try {
                        return ((double)(this[this.tableLinkPivotAdjustment.PAOGUpstreamPredictedColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'PAOGUpstreamPredicted\' in table \'LinkPivotAdjustment\' is DB" +
                                "Null.", e);
                    }
                }
                set {
                    this[this.tableLinkPivotAdjustment.PAOGUpstreamPredictedColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public double PAOGDownstreamPredicted {
                get {
                    try {
                        return ((double)(this[this.tableLinkPivotAdjustment.PAOGDownstreamPredictedColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'PAOGDownstreamPredicted\' in table \'LinkPivotAdjustment\' is " +
                                "DBNull.", e);
                    }
                }
                set {
                    this[this.tableLinkPivotAdjustment.PAOGDownstreamPredictedColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public double AOGUpstreamPredicted {
                get {
                    try {
                        return ((double)(this[this.tableLinkPivotAdjustment.AOGUpstreamPredictedColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'AOGUpstreamPredicted\' in table \'LinkPivotAdjustment\' is DBN" +
                                "ull.", e);
                    }
                }
                set {
                    this[this.tableLinkPivotAdjustment.AOGUpstreamPredictedColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public double AOGDownstreamPredicted {
                get {
                    try {
                        return ((double)(this[this.tableLinkPivotAdjustment.AOGDownstreamPredictedColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'AOGDownstreamPredicted\' in table \'LinkPivotAdjustment\' is D" +
                                "BNull.", e);
                    }
                }
                set {
                    this[this.tableLinkPivotAdjustment.AOGDownstreamPredictedColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string Location {
                get {
                    if (this.IsLocationNull()) {
                        return string.Empty;
                    }
                    else {
                        return ((string)(this[this.tableLinkPivotAdjustment.LocationColumn]));
                    }
                }
                set {
                    this[this.tableLinkPivotAdjustment.LocationColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string DownstreamSignalID {
                get {
                    if (this.IsDownstreamSignalIDNull()) {
                        return string.Empty;
                    }
                    else {
                        return ((string)(this[this.tableLinkPivotAdjustment.DownstreamSignalIDColumn]));
                    }
                }
                set {
                    this[this.tableLinkPivotAdjustment.DownstreamSignalIDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string DownstreamApproachDirection {
                get {
                    if (this.IsDownstreamApproachDirectionNull()) {
                        return string.Empty;
                    }
                    else {
                        return ((string)(this[this.tableLinkPivotAdjustment.DownstreamApproachDirectionColumn]));
                    }
                }
                set {
                    this[this.tableLinkPivotAdjustment.DownstreamApproachDirectionColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string UpstreamApproachDirection {
                get {
                    if (this.IsUpstreamApproachDirectionNull()) {
                        return string.Empty;
                    }
                    else {
                        return ((string)(this[this.tableLinkPivotAdjustment.UpstreamApproachDirectionColumn]));
                    }
                }
                set {
                    this[this.tableLinkPivotAdjustment.UpstreamApproachDirectionColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string ResultChartLocation {
                get {
                    if (this.IsResultChartLocationNull()) {
                        return string.Empty;
                    }
                    else {
                        return ((string)(this[this.tableLinkPivotAdjustment.ResultChartLocationColumn]));
                    }
                }
                set {
                    this[this.tableLinkPivotAdjustment.ResultChartLocationColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string DownstreamLocation {
                get {
                    try {
                        return ((string)(this[this.tableLinkPivotAdjustment.DownstreamLocationColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'DownstreamLocation\' in table \'LinkPivotAdjustment\' is DBNul" +
                                "l.", e);
                    }
                }
                set {
                    this[this.tableLinkPivotAdjustment.DownstreamLocationColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public double AOGTotalBefore {
                get {
                    try {
                        return ((double)(this[this.tableLinkPivotAdjustment.AOGTotalBeforeColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'AOGTotalBefore\' in table \'LinkPivotAdjustment\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableLinkPivotAdjustment.AOGTotalBeforeColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public double PAOGToatalBefore {
                get {
                    try {
                        return ((double)(this[this.tableLinkPivotAdjustment.PAOGToatalBeforeColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'PAOGToatalBefore\' in table \'LinkPivotAdjustment\' is DBNull." +
                                "", e);
                    }
                }
                set {
                    this[this.tableLinkPivotAdjustment.PAOGToatalBeforeColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public double AOGTotalPredicted {
                get {
                    try {
                        return ((double)(this[this.tableLinkPivotAdjustment.AOGTotalPredictedColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'AOGTotalPredicted\' in table \'LinkPivotAdjustment\' is DBNull" +
                                ".", e);
                    }
                }
                set {
                    this[this.tableLinkPivotAdjustment.AOGTotalPredictedColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public double PAOGTotalPredicted {
                get {
                    try {
                        return ((double)(this[this.tableLinkPivotAdjustment.PAOGTotalPredictedColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'PAOGTotalPredicted\' in table \'LinkPivotAdjustment\' is DBNul" +
                                "l.", e);
                    }
                }
                set {
                    this[this.tableLinkPivotAdjustment.PAOGTotalPredictedColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public int LinkNumber {
                get {
                    try {
                        return ((int)(this[this.tableLinkPivotAdjustment.LinkNumberColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'LinkNumber\' in table \'LinkPivotAdjustment\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableLinkPivotAdjustment.LinkNumberColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public double DownstreamVolume {
                get {
                    try {
                        return ((double)(this[this.tableLinkPivotAdjustment.DownstreamVolumeColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'DownstreamVolume\' in table \'LinkPivotAdjustment\' is DBNull." +
                                "", e);
                    }
                }
                set {
                    this[this.tableLinkPivotAdjustment.DownstreamVolumeColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public double UpstreamVolume {
                get {
                    try {
                        return ((double)(this[this.tableLinkPivotAdjustment.UpstreamVolumeColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'UpstreamVolume\' in table \'LinkPivotAdjustment\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableLinkPivotAdjustment.UpstreamVolumeColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsSignalIdNull() {
                return this.IsNull(this.tableLinkPivotAdjustment.SignalIdColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetSignalIdNull() {
                this[this.tableLinkPivotAdjustment.SignalIdColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsDeltaNull() {
                return this.IsNull(this.tableLinkPivotAdjustment.DeltaColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetDeltaNull() {
                this[this.tableLinkPivotAdjustment.DeltaColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsAdjustmentNull() {
                return this.IsNull(this.tableLinkPivotAdjustment.AdjustmentColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetAdjustmentNull() {
                this[this.tableLinkPivotAdjustment.AdjustmentColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsPAOGUpstreamBeforeNull() {
                return this.IsNull(this.tableLinkPivotAdjustment.PAOGUpstreamBeforeColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetPAOGUpstreamBeforeNull() {
                this[this.tableLinkPivotAdjustment.PAOGUpstreamBeforeColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsPAOGDownstreamBeforeNull() {
                return this.IsNull(this.tableLinkPivotAdjustment.PAOGDownstreamBeforeColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetPAOGDownstreamBeforeNull() {
                this[this.tableLinkPivotAdjustment.PAOGDownstreamBeforeColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsAOGUpstreamBeforeNull() {
                return this.IsNull(this.tableLinkPivotAdjustment.AOGUpstreamBeforeColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetAOGUpstreamBeforeNull() {
                this[this.tableLinkPivotAdjustment.AOGUpstreamBeforeColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsAOGDownstreamBeforeNull() {
                return this.IsNull(this.tableLinkPivotAdjustment.AOGDownstreamBeforeColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetAOGDownstreamBeforeNull() {
                this[this.tableLinkPivotAdjustment.AOGDownstreamBeforeColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsPAOGUpstreamPredictedNull() {
                return this.IsNull(this.tableLinkPivotAdjustment.PAOGUpstreamPredictedColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetPAOGUpstreamPredictedNull() {
                this[this.tableLinkPivotAdjustment.PAOGUpstreamPredictedColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsPAOGDownstreamPredictedNull() {
                return this.IsNull(this.tableLinkPivotAdjustment.PAOGDownstreamPredictedColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetPAOGDownstreamPredictedNull() {
                this[this.tableLinkPivotAdjustment.PAOGDownstreamPredictedColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsAOGUpstreamPredictedNull() {
                return this.IsNull(this.tableLinkPivotAdjustment.AOGUpstreamPredictedColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetAOGUpstreamPredictedNull() {
                this[this.tableLinkPivotAdjustment.AOGUpstreamPredictedColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsAOGDownstreamPredictedNull() {
                return this.IsNull(this.tableLinkPivotAdjustment.AOGDownstreamPredictedColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetAOGDownstreamPredictedNull() {
                this[this.tableLinkPivotAdjustment.AOGDownstreamPredictedColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsLocationNull() {
                return this.IsNull(this.tableLinkPivotAdjustment.LocationColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetLocationNull() {
                this[this.tableLinkPivotAdjustment.LocationColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsDownstreamSignalIDNull() {
                return this.IsNull(this.tableLinkPivotAdjustment.DownstreamSignalIDColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetDownstreamSignalIDNull() {
                this[this.tableLinkPivotAdjustment.DownstreamSignalIDColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsDownstreamApproachDirectionNull() {
                return this.IsNull(this.tableLinkPivotAdjustment.DownstreamApproachDirectionColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetDownstreamApproachDirectionNull() {
                this[this.tableLinkPivotAdjustment.DownstreamApproachDirectionColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsUpstreamApproachDirectionNull() {
                return this.IsNull(this.tableLinkPivotAdjustment.UpstreamApproachDirectionColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetUpstreamApproachDirectionNull() {
                this[this.tableLinkPivotAdjustment.UpstreamApproachDirectionColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsResultChartLocationNull() {
                return this.IsNull(this.tableLinkPivotAdjustment.ResultChartLocationColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetResultChartLocationNull() {
                this[this.tableLinkPivotAdjustment.ResultChartLocationColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsDownstreamLocationNull() {
                return this.IsNull(this.tableLinkPivotAdjustment.DownstreamLocationColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetDownstreamLocationNull() {
                this[this.tableLinkPivotAdjustment.DownstreamLocationColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsAOGTotalBeforeNull() {
                return this.IsNull(this.tableLinkPivotAdjustment.AOGTotalBeforeColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetAOGTotalBeforeNull() {
                this[this.tableLinkPivotAdjustment.AOGTotalBeforeColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsPAOGToatalBeforeNull() {
                return this.IsNull(this.tableLinkPivotAdjustment.PAOGToatalBeforeColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetPAOGToatalBeforeNull() {
                this[this.tableLinkPivotAdjustment.PAOGToatalBeforeColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsAOGTotalPredictedNull() {
                return this.IsNull(this.tableLinkPivotAdjustment.AOGTotalPredictedColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetAOGTotalPredictedNull() {
                this[this.tableLinkPivotAdjustment.AOGTotalPredictedColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsPAOGTotalPredictedNull() {
                return this.IsNull(this.tableLinkPivotAdjustment.PAOGTotalPredictedColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetPAOGTotalPredictedNull() {
                this[this.tableLinkPivotAdjustment.PAOGTotalPredictedColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsLinkNumberNull() {
                return this.IsNull(this.tableLinkPivotAdjustment.LinkNumberColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetLinkNumberNull() {
                this[this.tableLinkPivotAdjustment.LinkNumberColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsDownstreamVolumeNull() {
                return this.IsNull(this.tableLinkPivotAdjustment.DownstreamVolumeColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetDownstreamVolumeNull() {
                this[this.tableLinkPivotAdjustment.DownstreamVolumeColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsUpstreamVolumeNull() {
                return this.IsNull(this.tableLinkPivotAdjustment.UpstreamVolumeColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetUpstreamVolumeNull() {
                this[this.tableLinkPivotAdjustment.UpstreamVolumeColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        public class LinkPivotAdjustmentRowChangeEvent : global::System.EventArgs {
            
            private LinkPivotAdjustmentRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public LinkPivotAdjustmentRowChangeEvent(LinkPivotAdjustmentRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public LinkPivotAdjustmentRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591